---
kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  name: port-allow-30000
  namespace: opentofu
spec:
  podSelector: {}
  ingress:
  - ports:
    - port: 30000
  - from:
    - namespaceSelector:
        matchExpressions:
        - key: namespace
          operator: In
          values: ["flux-system"]
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: pe-demo
  namespace: opentofu
spec:
  interval: 30s
  url: https://github.com/alokhom/pe-demo
  ref:
    branch: main
---
apiVersion: infra.contrib.fluxcd.io/v1alpha2
kind: Terraform
metadata:
  name: pe-demo
  namespace: opentofu
spec:
  interval: 1m
  approvePlan: auto
  path: ./terraform-files
  sourceRef:
    kind: GitRepository
    name: pe-demo
    namespace: opentofu