apiVersion: v1
kind: ServiceAccount
metadata:
  name: dev-team
  namespace: apps
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: dev-team-reconciler
  namespace: apps
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
  - apiGroup: rbac.authorization.k8s.io
    kind: User
    name: gotk:apps:reconciler
  - kind: ServiceAccount
    name: dev-team
    namespace: apps
---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: OCIRepository
metadata:
  name: podinfo
  namespace: apps
spec:
  interval: 10m
  url: oci://ghcr.io/stefanprodan/charts/podinfo
  ref:
    semver: ">6.0.0"
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: podinfo
  namespace: apps
spec:
  serviceAccountName: dev-team
  interval: 10m
  chartRef:
    kind: OCIRepository
    name: podinfo
  values:
    hpa:
      enabled: true
      maxReplicas: 2
      cpu: 90